const daftarNamaGuru = [
    "Ahmad Diya'ul Hakkih",
    "Rodi",
    "Inayatun holidiah, S.Pd",
    "I'anatul Muhtaromah",
    "M. Hodri Ali Wafi",
    "Lala Anggi Dwi Agusti",
    "Adam Ramadhan",
    "Siti Mutmainnah",
    "Insanul Kamil",
    "Hakiki",
    "Luluk Lestari Nur'ainy",
    "Nadiah",
    "Alfan Ichwan Habibi",
    "Kurnia Nurandini Susilowati",
    "Devi Oktaviana",
    "Rahmat Hidayat",
    "Rahmattullah",
    "Latifah",
    "Sitti Salimah",
    "Zaenap",
    "Sitti Afrak",
    "Sitti Khotijah",
    "Anisatul Musrifah",
    "Abdul Kiflih",
    "Bi'iizetil kamilah",
    "Holipah",
    "Nur Holidah"
];
